### ISSUE TITLE
Maintenance and development status

### ISSUE THREAD

**Issue by Aposhian** [fedora-iot/zezere#124]
I see that there have been no substantial commits on this project for two years. What is the status of this project's development? Is it still under development as the README claims? Is the project in need of maintainers?

**Comment by nullr0ute** [comment]
It's been a bit slow due to availability of time of people. We're currently doing a summer outreachy project to move the underlying pieces over to support the FDO standard for on-boarding, this is just starting, will be happening here in a branch before becoming the main supported version once it's ready. We're always open to more contributors.
