### ISSUE TITLE
Rename and install manage.py

### ISSUE THREAD

**Issue by nullr0ute** [fedora-iot/zezere#34]
There's a manage.py utility used for various tasks, it's not installed by setup.py. We need to install it and it should also be renamed so it doesn't conflict with the world, Something like zezere-manage.py or similar.

**Comment by puiterwijk** [comment]
I was more leaning towards keeping manage.py in the repo and not shipping it (since it is used by Openshift's s2i python image to run Django-specific tasks), and instead add an entry-point to setup.py, so we'd get it automatically installed.
A blogpost about how this is done can be found at https://lincolnloop.com/blog/goodbye-managepy/ .

**Comment by puiterwijk** [comment]
I was more leaning towards keeping manage.py in the repo and not shipping it (since it is used by Openshift's s2i python image to run Django-specific tasks), and instead add an entry-point to setup.py, so we'd get it automatically installed.
A blogpost about how this is done can be found at https://lincolnloop.com/blog/goodbye-managepy/ .
